12: Etc/GMT-12
11: Etc/GMT-11
10: Etc/GMT-10
9: Etc/GMT-9
8: Etc/GMT-8
7: Etc/GMT-7
6: Etc/GMT-6
5: Etc/GMT-5
4: Etc/GMT-4
3: Etc/GMT-3
2: Etc/GMT-2
1: Etc/GMT-1
0: Etc/GMT
-1: Etc/GMT+1
-2: Etc/GMT+2
-3: Etc/GMT+3
-4: Etc/GMT+4
-5: Etc/GMT+5
-6: Etc/GMT+6
-7: Etc/GMT+7
-8: Etc/GMT+8
-9: Etc/GMT+9
-10: Etc/GMT+10
-11: Etc/GMT+11
-12: Etc/GMT+12
'13:45': Pacific/Chatham
'12:45': Pacific/Chatham
'11:30': Pacific/Norfolk
'10:30': Australia/Darwin
'9:30': Australia/Darwin
'6:30': Indian/Cocos
'5:45': Asia/Katmandu
'5:30': Asia/Calcutta
'4:30': Asia/Kabul
'3:30': Asia/Tehran
'-2:30': America/St_Johns
'-3:30': America/St_Johns
'-4:30': America/Caracas
'-9:30': Pacific/Marquesas

